version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-todo
    volumes:
      - ~/data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
